"""
Phase 5 ratcheted snapshot — the set of production files under
``hyperscale/distributed/`` that currently contain a direct call to
``time.X`` / ``asyncio.sleep`` / ``asyncio.wait_for`` /
non-crypto ``random.X``.

Each Phase 5b–5d migration commit removes its migrated file paths
from this set. The accompanying lint
``tests/simulation/lints/test_no_direct_time_random.py`` fails when
the discovered set differs from this snapshot in either direction,
so the snapshot must always reflect current state exactly.

Final state after Phase 5e: this set is empty.

Stored as Python (not a text snapshot) so the project's ``*.txt``
gitignore rule doesn't accidentally hide it from version control.
"""

EXPECTED_RUNTIME_VIOLATIONS: frozenset[str] = frozenset(
{
    "hyperscale/distributed/capacity/capacity_aggregator.py",
    "hyperscale/distributed/capacity/datacenter_capacity.py",
    "hyperscale/distributed/capacity/execution_time_estimator.py",
    "hyperscale/distributed/capacity/spillover_evaluator.py",
    "hyperscale/distributed/datacenters/cross_dc_correlation.py",
    "hyperscale/distributed/datacenters/datacenter_health_manager.py",
    "hyperscale/distributed/datacenters/lease_manager.py",
    "hyperscale/distributed/datacenters/manager_dispatcher.py",
    "hyperscale/distributed/discovery/discovery_service.py",
    "hyperscale/distributed/discovery/dns/negative_cache.py",
    "hyperscale/distributed/discovery/dns/resolver.py",
    "hyperscale/distributed/discovery/dns/security.py",
    "hyperscale/distributed/discovery/metrics/discovery_metrics.py",
    "hyperscale/distributed/discovery/models/peer_info.py",
    "hyperscale/distributed/discovery/pool/connection_pool.py",
    "hyperscale/distributed/discovery/pool/sticky_connection.py",
    "hyperscale/distributed/discovery/selection/ewma_tracker.py",
    "hyperscale/distributed/idempotency/gate_cache.py",
    "hyperscale/distributed/idempotency/idempotency_entry.py",
    "hyperscale/distributed/idempotency/manager_ledger.py",
    "hyperscale/distributed/jobs/core_allocator.py",
    "hyperscale/distributed/jobs/gates/gate_job_manager.py",
    "hyperscale/distributed/jobs/gates/gate_job_timeout_tracker.py",
    "hyperscale/distributed/jobs/gates/job_forwarding_tracker.py",
    "hyperscale/distributed/jobs/job_manager.py",
    "hyperscale/distributed/jobs/timeout_strategy.py",
    "hyperscale/distributed/jobs/windowed_stats_collector.py",
    "hyperscale/distributed/jobs/worker_dispatch_routing_state.py",
    "hyperscale/distributed/jobs/worker_drain_intent.py",
    "hyperscale/distributed/jobs/worker_pool.py",
    "hyperscale/distributed/jobs/workflow_dispatcher.py",
    "hyperscale/distributed/leases/job_lease.py",
    "hyperscale/distributed/ledger/job_id.py",
    "hyperscale/distributed/ledger/job_ledger.py",
    "hyperscale/distributed/ledger/pipeline/commit_pipeline.py",
    "hyperscale/distributed/ledger/wal/wal_writer.py",
    "hyperscale/distributed/models/coordinates.py",
    "hyperscale/distributed/models/jobs.py",
    "hyperscale/distributed/nodes/client/cancellation.py",
    "hyperscale/distributed/nodes/client/handlers/tcp_workflow_result.py",
    "hyperscale/distributed/nodes/client/leadership.py",
    "hyperscale/distributed/nodes/client/submission.py",
    "hyperscale/distributed/nodes/client/tracking.py",
    "hyperscale/distributed/nodes/gate/cancellation_coordinator.py",
    "hyperscale/distributed/nodes/gate/dispatch_coordinator.py",
    "hyperscale/distributed/nodes/gate/handlers/tcp_job.py",
    "hyperscale/distributed/nodes/gate/handlers/tcp_manager.py",
    "hyperscale/distributed/nodes/gate/health_coordinator.py",
    "hyperscale/distributed/nodes/gate/leadership_coordinator.py",
    "hyperscale/distributed/nodes/gate/models/job_forwarding_state.py",
    "hyperscale/distributed/nodes/gate/orphan_job_coordinator.py",
    "hyperscale/distributed/nodes/gate/peer_coordinator.py",
    "hyperscale/distributed/nodes/gate/replication_coordinator.py",
    "hyperscale/distributed/nodes/gate/server.py",
    "hyperscale/distributed/nodes/gate/state.py",
    "hyperscale/distributed/nodes/gate/stats_coordinator.py",
    "hyperscale/distributed/nodes/manager/cancellation.py",
    "hyperscale/distributed/nodes/manager/discovery.py",
    "hyperscale/distributed/nodes/manager/dispatch.py",
    "hyperscale/distributed/nodes/manager/handlers/tcp_cancellation.py",
    "hyperscale/distributed/nodes/manager/health.py",
    "hyperscale/distributed/nodes/manager/models/provision_state.py",
    "hyperscale/distributed/nodes/manager/rate_limiting.py",
    "hyperscale/distributed/nodes/manager/registry.py",
    "hyperscale/distributed/nodes/manager/server.py",
    "hyperscale/distributed/nodes/manager/stats.py",
    "hyperscale/distributed/nodes/manager/sync.py",
    "hyperscale/distributed/nodes/manager/worker_dissemination.py",
    "hyperscale/distributed/nodes/worker/background_loops.py",
    "hyperscale/distributed/nodes/worker/backpressure.py",
    "hyperscale/distributed/nodes/worker/cancellation.py",
    "hyperscale/distributed/nodes/worker/cluster_connection.py",
    "hyperscale/distributed/nodes/worker/discovery.py",
    "hyperscale/distributed/nodes/worker/execution.py",
    "hyperscale/distributed/nodes/worker/handlers/tcp_leader_transfer.py",
    "hyperscale/distributed/nodes/worker/health.py",
    "hyperscale/distributed/nodes/worker/lifecycle.py",
    "hyperscale/distributed/nodes/worker/progress.py",
    "hyperscale/distributed/nodes/worker/registry.py",
    "hyperscale/distributed/nodes/worker/server.py",
    "hyperscale/distributed/nodes/worker/state.py",
    "hyperscale/distributed/nodes/worker/workflow_executor.py",
    "hyperscale/distributed/raft/gate_raft_consensus.py",
    "hyperscale/distributed/raft/raft_consensus.py",
    "hyperscale/distributed/raft/raft_node.py",
    "hyperscale/distributed/raft/replicated_membership_log.py",
    "hyperscale/distributed/raft/replicated_stats_store.py",
    "hyperscale/distributed/reliability/backpressure.py",
    "hyperscale/distributed/reliability/best_effort_manager.py",
    "hyperscale/distributed/reliability/rate_limiting.py",
    "hyperscale/distributed/resources/health_piggyback.py",
    "hyperscale/distributed/resources/node_health_tracker.py",
    "hyperscale/distributed/routing/dispatch_time_tracker.py",
    "hyperscale/distributed/routing/routing_state.py",
    "hyperscale/distributed/runtime/real_clock.py",
    "hyperscale/distributed/runtime/real_random.py",
    "hyperscale/distributed/server/protocol/drop_counter.py",
    "hyperscale/distributed/swim/coordinates/coordinate_engine.py",
    "hyperscale/distributed/swim/coordinates/coordinate_tracker.py",
    "hyperscale/distributed/swim/core/audit.py",
    "hyperscale/distributed/swim/core/error_handler.py",
    "hyperscale/distributed/swim/core/metrics.py",
    "hyperscale/distributed/swim/core/node_id.py",
    "hyperscale/distributed/swim/core/resource_limits.py",
    "hyperscale/distributed/swim/core/state_embedder.py",
    "hyperscale/distributed/swim/detection/hierarchical_failure_detector.py",
    "hyperscale/distributed/swim/detection/incarnation_store.py",
    "hyperscale/distributed/swim/detection/incarnation_tracker.py",
    "hyperscale/distributed/swim/detection/indirect_probe_manager.py",
    "hyperscale/distributed/swim/detection/job_suspicion_manager.py",
    "hyperscale/distributed/swim/detection/peer_probe_reliability_tracker.py",
    "hyperscale/distributed/swim/detection/pending_indirect_probe.py",
    "hyperscale/distributed/swim/detection/suspicion_manager.py",
    "hyperscale/distributed/swim/detection/suspicion_state.py",
    "hyperscale/distributed/swim/detection/timing_wheel.py",
    "hyperscale/distributed/swim/gossip/extension_decision_gossip_buffer.py",
    "hyperscale/distributed/swim/gossip/extension_outcome_gossip_buffer.py",
    "hyperscale/distributed/swim/gossip/gossip_buffer.py",
    "hyperscale/distributed/swim/gossip/health_gossip_buffer.py",
    "hyperscale/distributed/swim/gossip/piggyback_update.py",
    "hyperscale/distributed/swim/gossip/worker_state_gossip_buffer.py",
    "hyperscale/distributed/swim/health_aware_server.py",
    "hyperscale/distributed/swim/health/federated_health_monitor.py",
    "hyperscale/distributed/swim/health/graceful_degradation.py",
    "hyperscale/distributed/swim/health/health_monitor.py",
    "hyperscale/distributed/swim/health/out_of_band_health_channel.py",
    "hyperscale/distributed/swim/health/peer_health_awareness.py",
    "hyperscale/distributed/swim/message_handling/membership/ack_handler.py",
    "hyperscale/distributed/swim/message_handling/membership/join_handler.py",
    "hyperscale/distributed/swim/message_handling/membership/leave_handler.py",
    "hyperscale/distributed/swim/message_handling/membership/nack_handler.py",
    "hyperscale/distributed/swim/message_handling/suspicion/alive_handler.py",
    "hyperscale/distributed/swim/roles/confirmation_manager.py",
    "hyperscale/distributed/taskex/models/shell_process.py",
    "hyperscale/distributed/taskex/models/task_run.py",
    "hyperscale/distributed/taskex/run.py",
    "hyperscale/distributed/taskex/task_runner.py",
    "hyperscale/distributed/taskex/task.py",
    "hyperscale/distributed/testing/workflows/long_running_workflow_test.py",
    "hyperscale/distributed/testing/workflows/long_running_workflow.py",
    "hyperscale/distributed/testing/workflows/simple_workflow.py",
    "hyperscale/distributed/workflow/state_machine.py",
    }
)
