"""Log calls handed to the task runner, per function, today (test_no_task_runner_logging)."""

EXPECTED_TASK_RUNNER_LOGGING_VIOLATIONS: dict[str, int] = {
    'hyperscale/distributed/nodes/gate/health_coordinator.py::GateHealthCoordinator._handle_partition_detected': 2,
    'hyperscale/distributed/nodes/gate/health_coordinator.py::GateHealthCoordinator._handle_partition_healed': 2,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_cohort_change': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_cross_dc_callback_error': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_dc_health_change': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_dc_leader_change': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_gate_become_leader': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_gate_lose_leadership': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_job_raft_leader': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_job_raft_lose_leader': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_node_dead': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_partition_detected': 1,
    'hyperscale/distributed/nodes/gate/server.py::GateServer._on_partition_healed': 1,
    'hyperscale/distributed/nodes/manager/server.py::ManagerServer._on_cohort_change': 1,
    'hyperscale/distributed/nodes/manager/server.py::ManagerServer._on_job_raft_leader': 1,
    'hyperscale/distributed/nodes/manager/server.py::ManagerServer._on_job_raft_lose_leader': 1,
    'hyperscale/distributed/nodes/worker/server.py::WorkerServer._on_peer_confirmed': 1,
    'hyperscale/distributed/nodes/worker/server.py::WorkerServer.request_extension': 1,
    'hyperscale/distributed/server/server/mercury_sync_base_server.py::MercurySyncBaseServer._on_tcp_task_done': 1,
    'hyperscale/distributed/server/server/mercury_sync_base_server.py::MercurySyncBaseServer._on_udp_task_done': 1,
    'hyperscale/distributed/server/server/mercury_sync_base_server.py::MercurySyncBaseServer._spawn_udp_response': 1,
    'hyperscale/distributed/server/server/mercury_sync_base_server.py::MercurySyncBaseServer.read_udp': 5,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer._handle_background_task_error': 1,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer._log_suspicion_expiration_diagnostic': 1,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer._on_become_leader': 1,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer._on_degradation_level_change': 1,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer._on_hierarchical_detector_error': 1,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer._on_leader_change': 2,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer._on_lose_leadership': 1,
    'hyperscale/distributed/swim/health_aware_server.py::HealthAwareServer.is_message_fresh': 1,
    'hyperscale/distributed/swim/leadership/local_leader_election.py::LocalLeaderElection._log_debug_sync': 1,
}
