apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperscale-manager.adminServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperscale-manager.labels" . | nindent 4 }}
    hyperscale.io/service-kind: admin
spec:
  type: ClusterIP
  selector:
    {{- include "hyperscale-manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: cluster
      port: {{ .Values.listen.port }}
      targetPort: cluster
      protocol: TCP
    - name: metrics
      port: {{ .Values.listen.metricsPort }}
      targetPort: metrics
      protocol: TCP
