version: '3.10'

services:
  hyperscale:
      build:
        context: ..
        dockerfile: ./.devcontainer/Dockerfile
        ssh:
          - default=${SSH_AUTH_SOCK}
      environment:
        - LD_LIBRARY_PATH=/usr/local/lib
      volumes:
        - ..:/workspace
        - ../.git:/workspace/.git
        - ../.devcontainer:/workspace/.devcontainer
        - ~/.aws:${HOME}/.aws
        - ~/.ssh:${HOME}/.ssh
        - ~/.git:${HOME}/.git
      ports:
        - 5003:5003
      stdin_open: true
      tty: true