"""Wire model ``JobSubmission`` -- pickled under the wire namespace
``hyperscale.distributed.models.distributed`` (see that module)."""

from typing import TYPE_CHECKING
from dataclasses import dataclass, field
from .message import Message

if TYPE_CHECKING:
    from hyperscale.distributed.resources.resource_budget import ResourceBudget


@dataclass(slots=True)
class JobSubmission(Message):
    """
    Job submission from client to gate or manager.

    A job contains one or more workflow classes to execute.

    Workflow format (cloudpickled):
        list[tuple[str, list[str], Workflow]]
        - str: workflow_id (client-generated, globally unique)
        - list[str]: dependency workflow names
        - Workflow: the workflow instance

    The workflow_id is generated by the client to ensure consistency across
    all datacenters. Gates and managers use these IDs to track and correlate
    results from different DCs for the same logical workflow.

    If callback_addr is provided, the gate/manager will push status
    updates to the client via TCP instead of requiring polling.

    If reporting_configs is provided (cloudpickled list of ReporterConfig),
    the manager/gate will submit results to reporters after aggregation
    and notify the client of success/failure per reporter.

    Protocol Version (AD-25):
    - protocol_version_major/minor: For version compatibility checks
    - capabilities: Comma-separated list of features client supports
    """

    job_id: str  # Unique job identifier
    workflows: bytes  # Cloudpickled list[tuple[str, list[str], Workflow]]
    vus: int  # Virtual users (cores to use per workflow)
    timeout_seconds: float  # Maximum execution time
    # Phase H2: distinguishes "client passed timeout_seconds explicitly"
    # from "client took the framework default." When False, the manager
    # falls back to:
    #   1. The workflow class's timeout if it was overridden from the
    #      base ``Workflow.timeout = "30s"`` default.
    #   2. Otherwise ``workflow.duration × HYPERSCALE_DEFAULT_WORKER_
    #      TIMEOUT_MULTIPLIER`` (default 1.5).
    # When True, ``timeout_seconds`` is honored verbatim regardless of
    # workflow-class settings. See AD-34 addendum (Phase H).
    timeout_seconds_explicit: bool = False
    datacenter_count: int = 1  # Number of DCs to run in (gates only)
    datacenters: list[str] = field(default_factory=list)
    # Optional callback address for push notifications
    # If set, server pushes status updates to this address
    callback_addr: tuple[str, int] | None = None
    # Origin gate address for direct DC-to-Job-Leader routing
    # Set by the job leader gate when dispatching to managers
    # Managers send results directly to this gate instead of all gates
    origin_gate_addr: tuple[str, int] | None = None
    # Optional reporter configs for result submission
    # Cloudpickled list of ReporterConfig objects
    # If set, manager/gate submits results to these reporters after aggregation
    reporting_configs: bytes = b""
    # Protocol version fields (AD-25) - defaults for backwards compatibility
    protocol_version_major: int = 1
    protocol_version_minor: int = 0
    capabilities: str = ""  # Comma-separated feature list
    # Idempotency key (AD-40) - if provided, gate uses idempotency cache to prevent duplicate processing
    idempotency_key: str | None = None
    # AD-44 retry budgets. 0 means "use the manager's configured
    # default" (RetryBudgetManager.create_budget resolves 0 through
    # retry_budget_default / retry_budget_per_workflow_default and caps
    # at the configured maxima), so an old client that never sets these
    # behaves exactly as before the fields existed.
    retry_budget: int = 0  # Total retry budget for the job
    retry_budget_per_workflow: int = 0  # Per-workflow retry cap
    # AD-41: resource limits each of this job's workflows is enforced
    # against; None applies the manager's configured default budget.
    resource_budget: "ResourceBudget | None" = None
    # AD-44 best-effort: complete once best_effort_min_dcs datacenters
    # completed or best_effort_deadline_seconds passed, instead of waiting
    # for every datacenter (0 = the gate's configured default for each).
    best_effort: bool = False
    best_effort_min_dcs: int = 0
    best_effort_deadline_seconds: float = 0.0
    # AD-36 mid-flight failover: a job's leader gate re-dispatches the
    # unfinished share of a datacenter it lost to another. Non-empty, the
    # manager runs only these workflows -- and every workflow they depend
    # on, re-run for the context their dependents read.
    rerun_workflow_ids: list[str] = field(default_factory=list)
