# This is a basic workflow to help you get started with Actions

name: Build Python Images

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - .github/workflows/build_docker_image.yml
      - docker/images/Dockerfile
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/build_docker_image.yml
      - docker/images/Dockerfile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  IMAGE_OS: "bookworm"
  PYTHON_VERSION: "3.13"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build_hyperscale_image_base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        file: docker/images/Dockerfile
        tags: hyperlightorg/hyperscale:latest
        build-args: |
          VERSION=${{env.PYTHON_VERSION}}
          BASE=${{env.IMAGE_OS}}
